apiVersion: concourse-ci.org/v1alpha1
kind: Instance
metadata:
  name: local
spec:
  url: http://localhost:8080
  auth:
    password:
      username: test
      passwordRef:
        name: concourse-local-credentials
        key: password
  healthProbeInterval: 1m
