apiVersion: concourse-ci.org/v1alpha1
kind: Team
metadata:
  name: my-team
spec:
  instanceRef:
    name: local
  teamName: main
  allowDestroy: false
  reclaimPolicy: Delete
  roles:
    - role: owner
      users:
        - local:test
