---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  - secrets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
- apiGroups:
  - concourse-ci.org
  resources:
  - builds
  - instances
  - jobs
  - pipelines
  - resources
  - teams
  - workers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - concourse-ci.org
  resources:
  - builds/finalizers
  - instances/finalizers
  - jobs/finalizers
  - pipelines/finalizers
  - resources/finalizers
  - teams/finalizers
  - workers/finalizers
  verbs:
  - update
- apiGroups:
  - concourse-ci.org
  resources:
  - builds/status
  - instances/status
  - jobs/status
  - pipelines/status
  - resources/status
  - teams/status
  - workers/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - delivery.maestro.sap.com
  resources:
  - lifecyclemanagers
  verbs:
  - create
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - delivery.maestro.sap.com
  resources:
  - lifecyclemanagers/status
  verbs:
  - get
  - patch
  - update
