{{- define "gvList" -}}
{{- $groupVersions := . -}}
---
# This file is auto-generated by crd-ref-docs. Do not edit manually.
# Run: make docs-generate
---

# API Reference

> This reference is auto-generated from the Go source at `api/v1alpha1/`. Run `make docs-generate` to regenerate.

## API Groups
{{- range $groupVersions }}
- {{ markdownRenderGVLink . }}
{{- end }}

{{ range $groupVersions }}
{{ template "gvDetails" . }}
{{ end }}

{{- end -}}
