apiVersion: concourse.concourse-ci.org/v1alpha1
kind: ConcoursePipeline
metadata:
  labels:
    app.kubernetes.io/name: concourse-operator
    app.kubernetes.io/managed-by: kustomize
  name: concoursepipeline-sample
spec:
  teamRef:
    name: concourseteam-sample
  pipelineName: hello-world
  config:
    inline: |
      jobs:
        - name: hello
          plan:
            - task: say-hello
              config:
                platform: linux
                image_resource:
                  type: registry-image
                  source:
                    repository: alpine
                run:
                  path: echo
                  args: ["Hello, World!"]
  paused: false
  exposed: false
