apiVersion: concourse.concourse-ci.org/v1alpha1
kind: ConcourseWorker
metadata:
  labels:
    app.kubernetes.io/name: concourse-operator
    app.kubernetes.io/managed-by: kustomize
  name: concourseworker-sample
spec:
  instanceRef:
    name: concourseinstance-sample
  workerName: worker-1
  desiredState: active
