## Append samples of your project ##
resources:
- concourse-ci.org_v1alpha1_instance.yaml
- concourse-ci.org_v1alpha1_team.yaml
- concourse-ci.org_v1alpha1_pipeline.yaml
- concourse-ci.org_v1alpha1_job.yaml
- concourse-ci.org_v1alpha1_build.yaml
- concourse-ci.org_v1alpha1_resource.yaml
- concourse-ci.org_v1alpha1_worker.yaml
# +kubebuilder:scaffold:manifestskustomizesamples
